---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy via Ansible

    steps:
      - uses: actions/checkout@v2

      - run: which ansible
      - run: ansible --version
      - run: echo $GITHUB_SHA

      - run: |
          mkdir -p ~/.ssh
          echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: ansible all -m ping -i tools/ansible/hosts.ini
        env:
          ANSIBLE_HOST_KEY_CHECKING: no

      # - run: echo ${{ secrets.ANSIBLE_VAULT_PASS }} > tools/ansible/.vault-pass.txt
      # - run: >
      #     ansible-playbook tools/ansible/deploy.yml
      #     -i tools/ansible/hosts.ini
      #     -e "app_version=$GITHUB_SHA"
      #     --vault-password-file=tools/ansible/.vault-pass.txt
      # - run: rm tools/ansible/.vault-pass.txt
