---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy via Ansible

    steps:
      - uses: actions/checkout@v2

      - run: which ansible
      - run: ansible --version
