---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy via Ansible

    steps:
      - uses: actions/checkout@v2

      - run: which ansible
      - run: ansible --version
      - run: echo $GITHUB_SHA

      - run: echo ${{ secrets.ANSIBLE_VAULT_PASS }} > tools/ansible/.vault-pass.txt
      - run: >
          ansible-playbook tools/ansible/deploy.yml
          -i tools/ansible/hosts.ini
          -e "app_version=$GITHUB_SHA"
          --vault-password-file=tools/ansible/.vault-pass.txt
      - run: rm tools/ansible/.vault-pass.txt
